language: rust
cache: cargo

branches:
  only:
    - master

rust:
  - stable

os:
  - linux
  - osx
  - windows

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - os: windows
  include:
    - name: "Rust: stable (wasm32)"
      rust: stable
      script: cargo build --all --target wasm32-unknown-unknown

install:
  - rustup component add rustfmt
  - rustup component add clippy
  - rustup target add wasm32-unknown-unknown

script:
  # lint
  - cargo fmt --version
  - cargo fmt --all -- --check
  - cargo clippy --version
  - cargo clippy --all

  # test
  - cargo test --all --release

  # doc build
  - cargo doc --no-deps
